name: CI/CD - Next.js NGP App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install dependencies and build
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Step 5: Build & push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USER }}/ngp-app:latest .
          docker push ${{ secrets.DOCKER_HUB_USER }}/ngp-app:latest

      # Step 6: Deploy to EC2
      - name: Deploy to EC2
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: bash deploy.sh
